# Generated by Django 2.0.6 on 2018-07-02 12:59

import Mirkolito.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mirkolito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='alumno',
            field=models.ForeignKey(on_delete=Mirkolito.models.Alumno, related_name='notas', to='Mirkolito.Alumno'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='curso',
            field=models.ForeignKey(on_delete=Mirkolito.models.Curso, related_name='cursonotas', to='Mirkolito.Curso'),
        ),
    ]
